2018-09-24T19:15:13.404-0500 I CONTROL  [initandlisten] MongoDB starting : pid=75094 port=27017 dbpath=/data/db 64-bit host=installminsMBP5
2018-09-24T19:15:13.404-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-09-24T19:15:13.404-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-09-24T19:15:13.405-0500 I CONTROL  [initandlisten] allocator: system
2018-09-24T19:15:13.405-0500 I CONTROL  [initandlisten] modules: none
2018-09-24T19:15:13.405-0500 I CONTROL  [initandlisten] build environment:
2018-09-24T19:15:13.405-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-09-24T19:15:13.405-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-09-24T19:15:13.405-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-09-24T19:15:13.407-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-09-24T19:15:13.407-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-09-24T19:15:14.290-0500 I STORAGE  [initandlisten] WiredTiger message [1537834514:290776][75094:0x7fffb08083c0], txn-recover: Main recovery loop: starting at 45/98432
2018-09-24T19:15:14.383-0500 I STORAGE  [initandlisten] WiredTiger message [1537834514:383195][75094:0x7fffb08083c0], txn-recover: Recovering log 45 through 46
2018-09-24T19:15:14.448-0500 I STORAGE  [initandlisten] WiredTiger message [1537834514:448522][75094:0x7fffb08083c0], txn-recover: Recovering log 46 through 46
2018-09-24T19:15:14.494-0500 I STORAGE  [initandlisten] WiredTiger message [1537834514:494702][75094:0x7fffb08083c0], txn-recover: Set global recovery timestamp: 0
2018-09-24T19:15:14.601-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-09-24T19:15:14.900-0500 I CONTROL  [initandlisten] 
2018-09-24T19:15:14.900-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-09-24T19:15:14.901-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-09-24T19:15:14.901-0500 I CONTROL  [initandlisten] 
2018-09-24T19:15:14.901-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-09-24T19:15:14.901-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-09-24T19:15:14.901-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-09-24T19:15:14.902-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-09-24T19:15:14.902-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-09-24T19:15:14.902-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-09-24T19:15:14.902-0500 I CONTROL  [initandlisten] 
2018-09-24T19:15:15.066-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-09-24T19:15:15.069-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-09-24T19:15:15.992-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:62327 #1 (1 connection now open)
2018-09-24T19:15:15.993-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:62327 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-09-24T19:15:16.556-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:62328 #2 (2 connections now open)
2018-09-24T19:15:16.557-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:62328 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-09-24T19:17:02.523-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:62490 #3 (3 connections now open)
2018-09-24T19:17:02.524-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:62490 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-09-24T19:17:47.549-0500 I NETWORK  [conn3] end connection 127.0.0.1:62490 (1 connection now open)
2018-09-24T19:17:47.549-0500 I NETWORK  [conn2] end connection 127.0.0.1:62328 (2 connections now open)
2018-09-24T19:17:48.029-0500 I NETWORK  [conn1] end connection 127.0.0.1:62327 (0 connections now open)
2018-09-24T19:17:48.059-0500 I CONTROL  [signalProcessingThread] got signal 15 (Terminated: 15), will terminate after current cmd ends
2018-09-24T19:17:48.059-0500 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2018-09-24T19:17:48.059-0500 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2018-09-24T19:17:48.060-0500 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2018-09-24T19:17:48.060-0500 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2018-09-24T19:17:48.062-0500 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2018-09-24T19:17:48.210-0500 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2018-09-24T19:17:48.211-0500 I CONTROL  [signalProcessingThread] now exiting
2018-09-24T19:17:48.211-0500 I CONTROL  [signalProcessingThread] shutting down with code:0
