2018-07-25T11:07:26.908-0500 I CONTROL  [initandlisten] MongoDB starting : pid=15840 port=27017 dbpath=/data/db 64-bit host=installadmins-MacBook-Pro-5.local
2018-07-25T11:07:26.909-0500 I CONTROL  [initandlisten] db version v4.0.0
2018-07-25T11:07:26.909-0500 I CONTROL  [initandlisten] git version: 3b07af3d4f471ae89e8186d33bbb1d5259597d51
2018-07-25T11:07:26.909-0500 I CONTROL  [initandlisten] allocator: system
2018-07-25T11:07:26.909-0500 I CONTROL  [initandlisten] modules: none
2018-07-25T11:07:26.910-0500 I CONTROL  [initandlisten] build environment:
2018-07-25T11:07:26.910-0500 I CONTROL  [initandlisten]     distarch: x86_64
2018-07-25T11:07:26.910-0500 I CONTROL  [initandlisten]     target_arch: x86_64
2018-07-25T11:07:26.910-0500 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, systemLog: { destination: "file", path: "../../bash/vocab/mongo_log/mongod.log" } }
2018-07-25T11:07:26.910-0500 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2018-07-25T11:07:26.911-0500 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7680M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
2018-07-25T11:07:27.794-0500 I STORAGE  [initandlisten] WiredTiger message [1532534847:794486][15840:0x7fffb42423c0], txn-recover: Main recovery loop: starting at 8/6400
2018-07-25T11:07:27.901-0500 I STORAGE  [initandlisten] WiredTiger message [1532534847:901896][15840:0x7fffb42423c0], txn-recover: Recovering log 8 through 9
2018-07-25T11:07:27.977-0500 I STORAGE  [initandlisten] WiredTiger message [1532534847:977559][15840:0x7fffb42423c0], txn-recover: Recovering log 9 through 9
2018-07-25T11:07:28.030-0500 I STORAGE  [initandlisten] WiredTiger message [1532534848:30487][15840:0x7fffb42423c0], txn-recover: Set global recovery timestamp: 0
2018-07-25T11:07:28.134-0500 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
2018-07-25T11:07:28.287-0500 I CONTROL  [initandlisten] 
2018-07-25T11:07:28.287-0500 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2018-07-25T11:07:28.287-0500 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2018-07-25T11:07:28.287-0500 I CONTROL  [initandlisten] 
2018-07-25T11:07:28.288-0500 I CONTROL  [initandlisten] ** WARNING: This server is bound to localhost.
2018-07-25T11:07:28.288-0500 I CONTROL  [initandlisten] **          Remote systems will be unable to connect to this server. 
2018-07-25T11:07:28.288-0500 I CONTROL  [initandlisten] **          Start the server with --bind_ip <address> to specify which IP 
2018-07-25T11:07:28.288-0500 I CONTROL  [initandlisten] **          addresses it should serve responses from, or with --bind_ip_all to
2018-07-25T11:07:28.289-0500 I CONTROL  [initandlisten] **          bind to all interfaces. If this behavior is desired, start the
2018-07-25T11:07:28.289-0500 I CONTROL  [initandlisten] **          server with --bind_ip 127.0.0.1 to disable this warning.
2018-07-25T11:07:28.289-0500 I CONTROL  [initandlisten] 
2018-07-25T11:07:28.460-0500 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2018-07-25T11:07:28.461-0500 I NETWORK  [initandlisten] waiting for connections on port 27017
2018-07-25T11:07:29.167-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60354 #1 (1 connection now open)
2018-07-25T11:07:29.167-0500 I NETWORK  [conn1] received client metadata from 127.0.0.1:60354 conn1: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-07-25T11:07:29.168-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60355 #2 (2 connections now open)
2018-07-25T11:07:29.169-0500 I NETWORK  [conn2] received client metadata from 127.0.0.1:60355 conn2: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-07-25T11:07:29.170-0500 I COMMAND  [conn2] dropDatabase vocab - starting
2018-07-25T11:07:29.170-0500 I COMMAND  [conn2] dropDatabase vocab - dropping 0 collections
2018-07-25T11:07:29.219-0500 I COMMAND  [conn2] dropDatabase vocab - finished
2018-07-25T11:07:29.957-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60356 #3 (3 connections now open)
2018-07-25T11:07:29.957-0500 I NETWORK  [conn3] received client metadata from 127.0.0.1:60356 conn3: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-07-25T11:07:29.958-0500 I NETWORK  [listener] connection accepted from 127.0.0.1:60357 #4 (4 connections now open)
2018-07-25T11:07:29.958-0500 I NETWORK  [conn4] received client metadata from 127.0.0.1:60357 conn4: { driver: { name: "PyMongo", version: "3.7.1" }, os: { type: "Darwin", name: "Darwin", architecture: "x86_64", version: "10.12.5" }, platform: "CPython 3.6.3.final.0" }
2018-07-25T11:07:43.463-0500 I STORAGE  [conn4] createCollection: vocab.Quiz with generated UUID: c042c95c-81e8-47e7-8c1d-a1f1b644579e
2018-07-25T11:07:43.535-0500 I NETWORK  [conn4] end connection 127.0.0.1:60357 (3 connections now open)
2018-07-25T11:07:43.535-0500 I NETWORK  [conn3] end connection 127.0.0.1:60356 (2 connections now open)
2018-07-25T11:08:40.632-0500 I NETWORK  [conn1] end connection 127.0.0.1:60354 (0 connections now open)
2018-07-25T11:08:40.632-0500 I NETWORK  [conn2] end connection 127.0.0.1:60355 (1 connection now open)
